### ISSUE TITLE
[Urgent] Cannot retrieve sgRNA plus missing "clear history/refresh" button?

### ISSUE THREAD

**Issue by congle25** [emmazchen/crispr-gpt-tracker#6]
This is urgent. I just tried meta-mode design guideRNA for human EMX1 and EGFR, but has error retrieving sgRNA sequence? Also there's no longer a clear / refresh button, is this removed intentionally? 

@emmazchen can you also check if this is issue for yo?
@zhanhugo can you help check/fix the 2 things?

<img width="610" alt="image" src="https://github.com/emmazchen/crispr-gpt-tracker/assets/7317829/d518fce1-a0a7-4891-86ed-dfcf66a42169">

<img width="527" alt="image" src="https://github.com/emmazchen/crispr-gpt-tracker/assets/7317829/3b28d591-45a2-4689-86d3-84f891e08199">

**Comment by emmazchen** [comment]
I'm also having this issue
<img width="1153" alt="Screenshot 2024-05-22 at 10 31 25 AM" src="https://github.com/emmazchen/crispr-gpt-tracker/assets/114841242/62a66570-6fa4-4c94-8111-796a624b1459">

<img width="1149" alt="Screenshot 2024-05-22 at 10 36 18 AM" src="https://github.com/emmazchen/crispr-gpt-tracker/assets/114841242/3cae542e-119f-410b-ab76-30c5848f58ff">

**Comment by zhanhugo** [comment]
1. <img width="1728" alt="Screenshot 2024-05-22 at 11 25 54 AM" src="https://github.com/emmazchen/crispr-gpt-tracker/assets/42554019/9024d1eb-40b4-4ec3-b6aa-343b67350bf8">
I was able to obtain results, but trying the same request multiple times yield inconsistent results, it actually gave me "Sorry, we could not find a sgRNA for you in our database" quite a few times. I have not extensively looked at the implmentation details for the sgrna function, I will do some investigation there.

2. The reset button was removed intentionally because there is a start new chat functionality now so no need to reset the chat.
